### ISSUE TITLE
De/serialize Vec<u8> as bytes()

### ISSUE THREAD

**Issue by gaetanww** [davidhewitt/pythonize#15]
Is it possible to serialize and deserialize rust's `Vec<u8>` as python `bytes()`?

**Comment by davidhewitt** [comment]
Thanks for the question, and sorry I took a few days to reply.

I don't think it's possible for `Vec<u8>` to serialize as `bytes` type, because the exact code path for `Vec<u8>` is defined by serde, which serializes `Vec<u8>` as a sequence of numbers.

I suggest you instead use the [`bytes::Bytes`](https://docs.rs/bytes/1.0.1/bytes/struct.Bytes.html) type, which does serialize to Python bytes.
